# Generated by Django 3.0.6 on 2020-06-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200602_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='category',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
