# Generated by Django 3.0.6 on 2020-06-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_pedido_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='topping',
            field=models.ManyToManyField(blank=True, related_name='Pedido_toppings', to='orders.Topping'),
        ),
    ]
