# Generated by Django 3.0.7 on 2020-06-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('I', 'Iniciated'), ('F', 'Finished'), ('D', 'delete')], default='Iniciated', max_length=64),
        ),
    ]
