# Generated by Django 3.0.7 on 2020-06-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200604_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('I', 'Iniciated'), ('F', 'Finished')], default='Iniciated', max_length=64),
        ),
    ]
