# Generated by Django 3.0.7 on 2020-06-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200604_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numberOrder',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
